version: "3.9"

services:
  weavefeed_accounts_db:
    image: postgres:16
    container_name: weavefeed_accounts_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/accounts:/var/lib/postgresql/data

  weavefeed_accounts_adminer:
    image: adminer:latest
    container_name: weavefeed_accounts_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - weavefeed_accounts_db
