name: Validate Accounts Service

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  accounts-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes in accounts service
        id: detect
        run: |
          echo "Checking for changes in service/accounts/ or tests/accounts/"
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} \
            ${{ github.event.pull_request.head.sha }} \
              | grep -qE '^service/accounts/|^tests/accounts/'; then
            echo "accounts_svc_changed=true" >> $GITHUB_OUTPUT
            echo "[INFO] service/accounts or tests/accounts has changed"
          else
            echo "accounts_svc_changed=false" >> $GITHUB_OUTPUT
            echo "[INFO] No changes detected in accounts service"
          fi

      - name: Set up Python
        if: steps.detect.outputs.accounts_svc_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        if: steps.detect.outputs.accounts_svc_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          if [ -f service/accounts/requirements.txt ]; then pip install -r service/accounts/requirements.txt; fi
          pip install ruff

      - name: Ruff (accounts only)
        if: steps.detect.outputs.accounts_svc_changed == 'true'
        run: ruff check service/accounts tests/accounts

      - name: Unit tests (accounts only)
        if: steps.detect.outputs.accounts_svc_changed == 'true'
        run: python -m unittest discover -s tests/accounts -p "test_*.py" -v
